import {create} from 'zustand';
import {createJSONStorage, persist} from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {get, post, put, setTokenGetter} from '../lib/api';
import type {Entitlements, TokenResponse, User} from '../lib/types';
export const GUEST_ENTITLEMENTS: Entitlements = {plan: 'free', is_premium: false, ads_enabled: true, max_quality_kbps: 128, skips_per_hour: 6, daily_picks: null, offline_downloads: false, equalizer: false, premium_content_access: 'preview', preview_seconds: 90};
interface AuthState {token: string | null; user: User | null; entitlements: Entitlements | null; hydrated: boolean; setSession: (response: TokenResponse) => void; refreshMe: () => Promise<void>; logout: () => Promise<void>; updateProfile: (data: Partial<Pick<User, 'name' | 'phone' | 'locale' | 'preferences'>>) => Promise<void>}
export const useAuth = create<AuthState>()(persist((set, getState) => ({token: null, user: null, entitlements: null, hydrated: false, setSession: response => {set({token: response.token, user: response.user, entitlements: response.user.entitlements || null}); void getState().refreshMe();}, refreshMe: async () => {if (!getState().token) return; try {const response = await get<{data: User}>('/auth/me'); set({user: response.data, entitlements: response.data.entitlements || null});} catch (error) {if ((error as any)?.status === 401) set({token: null, user: null, entitlements: null});}}, logout: async () => {try {await post('/auth/logout');} catch {} set({token: null, user: null, entitlements: null});}, updateProfile: async data => {await put('/auth/profile', data); await getState().refreshMe();}}), {name: 'betar.auth', storage: createJSONStorage(() => AsyncStorage), partialize: state => ({token: state.token, user: state.user, entitlements: state.entitlements}), onRehydrateStorage: () => state => {state?.hydrated !== undefined && useAuth.setState({hydrated: true}); if (state?.token) void useAuth.getState().refreshMe();}}));
setTokenGetter(() => useAuth.getState().token);
export function currentEntitlements() { return useAuth.getState().entitlements || GUEST_ENTITLEMENTS; }
