import { create } from 'zustand';
import { post } from '../lib/api';
import { useUi } from './ui';
import type { LiveTokenResponse } from '../lib/types';
interface LiveState { channelId:number|null; channelTitle:string|null; status:'idle'|'connecting'|'live'|'error'; volume:number; muted:boolean; audioBlocked:boolean; canSpeak:boolean; micOn:boolean; handRaised:boolean; connect:(id:number,title:string)=>Promise<void>; disconnect:()=>void; setVolume:(v:number)=>void; toggleMute:()=>void; resumeAudio:()=>Promise<void>; setMic:(on:boolean)=>Promise<void>; raiseHand:()=>Promise<void>; lowerHand:()=>Promise<void>; }
let room:any=null; let audioSession:any=null; let generation=0;
function setRemoteVolume(volume:number, muted=getState().muted) { room?.remoteParticipants?.forEach((p:any)=>p.audioTrackPublications?.forEach((pub:any)=>{ try { pub.track?.setVolume?.(muted?0:volume); } catch {/* best effort */} })); }
function getState(){return useLive.getState();}
export const useLive=create<LiveState>((set,get)=>({channelId:null,channelTitle:null,status:'idle',volume:.9,muted:false,audioBlocked:false,canSpeak:false,micOn:false,handRaised:false,
 connect:async(id,title)=>{const attempt=++generation;const old=room;room=null;try{old?.disconnect();}catch{/* noop */}try{await audioSession?.stopAudioSession?.();}catch{/* noop */}set({channelId:id,channelTitle:title,status:'connecting',audioBlocked:false,canSpeak:false,micOn:false,handRaised:false});try{const creds=await post<LiveTokenResponse>(`/live-channels/${id}/token`);if(attempt!==generation)return;const rn=await import('@livekit/react-native');(rn as any).registerGlobals?.();audioSession=(rn as any).AudioSession;await audioSession?.startAudioSession?.();const lk=await import('livekit-client');const r=new lk.Room({adaptiveStream:true,dynacast:true});if(attempt!==generation){r.disconnect();return;}room=r;
  r.on(lk.RoomEvent.TrackSubscribed,(track:any)=>{if(track.kind==='audio'&&room===r){try{track.setVolume?.(get().muted?0:get().volume);}catch{/* noop */}}});
  r.on(lk.RoomEvent.ParticipantPermissionsChanged,(_prev:any,p:any)=>{if(room!==r||attempt!==generation)return;const participant=p||r.localParticipant;if(participant!==r.localParticipant)return;const can=!!r.localParticipant.permissions?.canPublish;if(can){set({canSpeak:true,handRaised:false});useUi.getState().toast("You've been invited to speak — tap the mic to talk.",'success');}else{if(get().micOn)void r.localParticipant.setMicrophoneEnabled(false).catch(()=>undefined);set({canSpeak:false,micOn:false,handRaised:false});}});
  r.on(lk.RoomEvent.Disconnected,()=>{if(room!==r||attempt!==generation)return;room=null;void audioSession?.stopAudioSession?.();set({status:'idle',channelId:null,channelTitle:null,canSpeak:false,micOn:false,handRaised:false});});
  await r.connect(creds.ws_url,creds.token);if(room!==r||attempt!==generation){r.disconnect();return;}set({status:'live',canSpeak:!!r.localParticipant.permissions?.canPublish,audioBlocked:false});
 }catch(e){if(attempt!==generation)return;try{room?.disconnect();}catch{/* noop */}room=null;set({status:'error',audioBlocked:false,channelId:null,channelTitle:null,canSpeak:false,micOn:false,handRaised:false});useUi.getState().toast('Could not connect to the live broadcast.','error');}},
 disconnect:()=>{++generation;const r=room;room=null;try{r?.disconnect();}catch{/* noop */}void audioSession?.stopAudioSession?.();set({status:'idle',audioBlocked:false,channelId:null,channelTitle:null,canSpeak:false,micOn:false,handRaised:false});},
 setVolume:v=>{const volume=Math.max(0,Math.min(1,v));setRemoteVolume(volume,false);set({volume,muted:false});},toggleMute:()=>{const muted=!get().muted;setRemoteVolume(get().volume,muted);set({muted});},
 resumeAudio:async()=>{try{await room?.startAudio?.();setRemoteVolume(get().volume,get().muted);set({audioBlocked:false});}catch{set({audioBlocked:true});}},
 setMic:async on=>{if(!room||on&&!get().canSpeak)return;try{await room.localParticipant.setMicrophoneEnabled(on);set({micOn:on});}catch{set({micOn:false});useUi.getState().toast('Could not access your microphone.','error');}},
 raiseHand:async()=>{const id=get().channelId;if(id==null||!room)return;try{const lp=room.localParticipant;await post(`/live-channels/${id}/raise-hand`,{identity:lp.identity,name:lp.name||'Listener'});set({handRaised:true});useUi.getState().toast('Hand raised — waiting for the host to let you speak.','success');}catch{useUi.getState().toast('Could not send your request. Try again.','error');}},
 lowerHand:async()=>{const id=get().channelId;set({handRaised:false});if(id!=null&&room)void post(`/live-channels/${id}/lower-hand`,{identity:room.localParticipant.identity}).catch(()=>undefined);}
}));
