import {create} from 'zustand';
import {createJSONStorage, persist} from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type {PlayerTrack} from './player';
export type ToastKind = 'info' | 'success' | 'error' | 'premium';
export type PortalId = 'listen' | 'watch' | 'news';
export interface Toast {id: number; message: string; kind: ToastKind}
export interface UpgradeReason {title: string; body: string}
interface UiState {locale: 'en' | 'bn'; setLocale: (locale: 'en' | 'bn') => void; theme: 'light' | 'dark'; setTheme: (theme: 'light' | 'dark') => void; toggleTheme: () => void; portal: PortalId; setPortal: (portal: PortalId) => void; loginPromptOpen: boolean; loginPromptMessage: string | null; openLoginPrompt: (message?: string) => void; closeLoginPrompt: () => void; upgradePromptOpen: boolean; upgradeReason: UpgradeReason | null; openUpgradePrompt: (reason?: UpgradeReason) => void; closeUpgradePrompt: () => void; addToPlaylistTrack: PlayerTrack | null; openAddToPlaylist: (track: PlayerTrack) => void; closeAddToPlaylist: () => void; queuePanelOpen: boolean; toggleQueuePanel: () => void; nowPlayingOpen: boolean; setNowPlayingOpen: (open: boolean) => void; toasts: Toast[]; toast: (message: string, kind?: ToastKind) => void; dismissToast: (id: number) => void}
let sequence = 1;
export const useUi = create<UiState>()(persist((set, get) => ({locale: 'en', setLocale: locale => set({locale}), theme: 'dark', setTheme: theme => set({theme}), toggleTheme: () => set(s => ({theme: s.theme === 'dark' ? 'light' : 'dark'})), portal: 'listen', setPortal: portal => set({portal}), loginPromptOpen: false, loginPromptMessage: null, openLoginPrompt: message => set({loginPromptOpen: true, loginPromptMessage: message || null}), closeLoginPrompt: () => set({loginPromptOpen: false, loginPromptMessage: null}), upgradePromptOpen: false, upgradeReason: null, openUpgradePrompt: reason => set({upgradePromptOpen: true, upgradeReason: reason || null}), closeUpgradePrompt: () => set({upgradePromptOpen: false, upgradeReason: null}), addToPlaylistTrack: null, openAddToPlaylist: track => set({addToPlaylistTrack: track}), closeAddToPlaylist: () => set({addToPlaylistTrack: null}), queuePanelOpen: false, toggleQueuePanel: () => set(s => ({queuePanelOpen: !s.queuePanelOpen, nowPlayingOpen: false})), nowPlayingOpen: false, setNowPlayingOpen: nowPlayingOpen => set({nowPlayingOpen, queuePanelOpen: false}), toasts: [], toast: (message, kind = 'info') => {const id = sequence++; set(s => ({toasts: [...s.toasts.slice(-3), {id, message, kind}]})); setTimeout(() => get().dismissToast(id), 4200);}, dismissToast: id => set(s => ({toasts: s.toasts.filter(toast => toast.id !== id)}))}), {name: 'betar.ui', storage: createJSONStorage(() => AsyncStorage), partialize: state => ({locale: state.locale, theme: state.theme})}));
