import React from 'react';
import {ActivityIndicator, Image, Pressable, RefreshControlProps, ScrollView, StyleProp, StyleSheet, Text, TextInput, TextInputProps, View, ViewStyle} from 'react-native';
import {useUi, type PortalId} from '../stores/ui';
import {useResponsiveLayout} from '../lib/responsive';
import {mediaUrl} from '../lib/api';
const darkBase = {bg: '#070708', sunken: '#030304', surface: '#0f0f12', elevated: '#17171c', highlight: '#212129', text: '#f5f5f6', secondary: '#a5a5b0', muted: '#67676f', border: '#232329', borderStrong: '#34343d', danger: '#fb4d63', premium: '#f0b90b'};
const lightBase = {bg: '#f3f4f6', sunken: '#e9ebef', surface: '#ffffff', elevated: '#f7f8fa', highlight: '#eceff3', text: '#15171b', secondary: '#505560', muted: '#707681', border: '#dde0e5', borderStrong: '#c5cad2', danger: '#bd2942', premium: '#8a6100'};
const accents: Record<PortalId, {accent: string; soft: string; accentForeground: string}> = {listen: {accent: '#d43b55', soft: '#f8dfe3', accentForeground: '#ffffff'}, news: {accent: '#3f63e8', soft: '#dce5ff', accentForeground: '#ffffff'}, watch: {accent: '#38bfc1', soft: '#d7f4f2', accentForeground: '#062e30'}};
export function useTheme() { const theme = useUi(s => s.theme); const portal = useUi(s => s.portal); return {...(theme === 'light' ? lightBase : darkBase), ...accents[portal], header: theme === 'light' ? '#eef0f3' : '#292a2f', portal, theme, accentGlow: `${accents[portal].accent}52`}; }
export function Screen({children, refreshing, onRefresh, refreshControl}: {children: React.ReactNode; refreshing?: boolean; onRefresh?: () => void; refreshControl?: React.ReactElement<RefreshControlProps>}) { const colors = useTheme(); const layout = useResponsiveLayout(); return <ScrollView style={{flex: 1, backgroundColor: colors.bg}} contentContainerStyle={[styles.screen, layout.pageStyle, {paddingBottom: layout.compact ? 86 : 94}]} refreshControl={refreshControl || (onRefresh ? <RefreshControlCompat refreshing={Boolean(refreshing)} onRefresh={onRefresh} /> : undefined)} keyboardShouldPersistTaps="handled">{children}</ScrollView>; }
function RefreshControlCompat({refreshing, onRefresh}: {refreshing: boolean; onRefresh: () => void}) { const colors = useTheme(); return <RefreshControl tintColor={colors.accent} refreshing={refreshing} onRefresh={onRefresh} />; }
// Kept separate to keep the public Screen API small while still allowing RN's refresh control.
function RefreshControl(props: any) { const NativeRefresh = require('react-native').RefreshControl; return <NativeRefresh {...props} />; }
export function Heading({children, style}: {children: React.ReactNode; style?: StyleProp<any>}) { const colors = useTheme(); return <Text style={[styles.heading, {color: colors.text}, style]}>{children}</Text>; }
export function Label({children, muted = false, style}: {children: React.ReactNode; muted?: boolean; style?: StyleProp<any>}) { const colors = useTheme(); return <Text style={[styles.label, {color: muted ? colors.muted : colors.text}, style]}>{children}</Text>; }
export function Button({title, onPress, secondary = false, disabled = false, loading = false}: {title: string; onPress: () => void; secondary?: boolean; disabled?: boolean; loading?: boolean}) { const colors = useTheme(); return <Pressable disabled={disabled || loading} onPress={onPress} style={[styles.button, {backgroundColor: secondary ? colors.elevated : colors.accent, borderColor: secondary ? colors.border : colors.accent, opacity: disabled ? 0.45 : 1}]}><Text style={[styles.buttonText, {color: secondary ? colors.text : colors.accentForeground}]}>{loading ? 'Loading…' : title}</Text></Pressable>; }
export function Field({label, ...props}: TextInputProps & {label?: string}) { const colors = useTheme(); return <View style={styles.field}>{label ? <Label muted>{label}</Label> : null}<TextInput {...props} placeholderTextColor={props.placeholderTextColor || colors.muted} style={[styles.input, {backgroundColor: colors.surface, color: colors.text, borderColor: colors.border}, props.style]} /></View>; }
export function Card({children, onPress, style}: {children: React.ReactNode; onPress?: () => void; style?: StyleProp<ViewStyle>}) { const colors = useTheme(); const content = <View style={[styles.card, {backgroundColor: colors.surface, borderColor: colors.border}, style]}>{children}</View>; return onPress ? <Pressable onPress={onPress}>{content}</Pressable> : content; }
export function Row({children}: {children: React.ReactNode}) { return <View style={styles.row}>{children}</View>; }
export function Artwork({uri, size = 72, wide = false}: {uri?: string | null; size?: number; wide?: boolean}) { const colors = useTheme(); const source = mediaUrl(uri); return source ? <Image source={{uri: source}} style={{width: wide ? size * 1.8 : size, height: size, borderRadius: 14, backgroundColor: colors.elevated}} /> : <View style={{width: wide ? size * 1.8 : size, height: size, borderRadius: 14, backgroundColor: colors.elevated, alignItems: 'center', justifyContent: 'center'}}><Text style={{fontSize: size * .34, color: colors.muted}}>♫</Text></View>; }
export function Loading() { const colors = useTheme(); return <ActivityIndicator color={colors.accent} size="large" style={{marginVertical: 36}} />; }
export function ErrorView({error, onRetry}: {error?: string; onRetry?: () => void}) { const colors = useTheme(); return <Card style={{marginVertical: 20}}><Text style={[styles.error, {color: colors.danger}]}>{error || 'Something went wrong.'}</Text>{onRetry ? <Button title="Try again" secondary onPress={onRetry} /> : null}</Card>; }
export function Empty({title, detail, action}: {title: string; detail?: string; action?: React.ReactNode}) { const colors = useTheme(); return <View style={styles.empty}><Text style={[styles.emptyTitle, {color: colors.text}]}>{title}</Text>{detail ? <Text style={[styles.emptyDetail, {color: colors.muted}]}>{detail}</Text> : null}{action ? <View style={{marginTop: 16}}>{action}</View> : null}</View>; }
const styles = StyleSheet.create({screen: {padding: 18, paddingBottom: 135}, heading: {fontSize: 27, lineHeight: 33, fontWeight: '900', letterSpacing: -.4}, label: {fontSize: 12, fontWeight: '600'}, button: {borderWidth: 1, minHeight: 44, borderRadius: 12, paddingHorizontal: 17, alignItems: 'center', justifyContent: 'center'}, buttonText: {fontSize: 14, fontWeight: '800'}, field: {gap: 6, marginBottom: 14}, input: {borderWidth: 1, borderRadius: 12, paddingHorizontal: 13, paddingVertical: 11, fontSize: 15}, card: {borderWidth: 1, borderRadius: 15, padding: 13, gap: 8, marginBottom: 14}, row: {flexDirection: 'row', alignItems: 'center', gap: 10}, error: {fontWeight: '700', marginBottom: 12}, empty: {alignItems: 'center', justifyContent: 'center', paddingVertical: 45, paddingHorizontal: 24}, emptyTitle: {fontSize: 18, fontWeight: '800', textAlign: 'center'}, emptyDetail: {fontSize: 14, lineHeight: 20, textAlign: 'center', marginTop: 7}});
